[hk]
#海康配置
ip = "192.168.90.66"
port = 8000
user = "admin"
password = "shw12345"

[redis]
ip = "192.168.90.58"
port = 6379
auth = "123456"

[data_center]
#数据中心地址
addr = "localhost:50001"

[system]
#常规
face_score = 0.65

#是否显示摄像机,1为显示，其他值为不显示
show_camera = 0

#陌生人推送时间，单位是毫秒
stranger_push_time = 120000

#是否推送陌生人,为1表示推送，其他值不推送
is_push_stranger = 0

#注册员工推送时间，单位是毫秒
employee_push_time = 12000

#取帧频率
frame_frequency = 5

#每一个线程处理的人脸数
per_face_process_num = 100

#延迟多少分钟更新人脸库，当收到数据中心更新的时候
#单位是分钟
delay_upadte_time = 10








