// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dc_rpc.proto

#include "dc_rpc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_dc_5frpc_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_dc_5frpc_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_UserParam;
}  // namespace protobuf_dc_5frpc_2eproto
namespace proto {
class EmptyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Empty>
      _instance;
} _Empty_default_instance_;
class UpdateNotityDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UpdateNotity>
      _instance;
} _UpdateNotity_default_instance_;
class FeatureDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Feature>
      _instance;
} _Feature_default_instance_;
class UserParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UserParam>
      _instance;
} _UserParam_default_instance_;
class StorageReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StorageReply>
      _instance;
} _StorageReply_default_instance_;
}  // namespace proto
namespace protobuf_dc_5frpc_2eproto {
static void InitDefaultsEmpty() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_Empty_default_instance_;
    new (ptr) ::proto::Empty();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Empty::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Empty =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsEmpty}, {}};

static void InitDefaultsUpdateNotity() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_UpdateNotity_default_instance_;
    new (ptr) ::proto::UpdateNotity();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::UpdateNotity::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UpdateNotity =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUpdateNotity}, {}};

static void InitDefaultsFeature() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_Feature_default_instance_;
    new (ptr) ::proto::Feature();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Feature::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Feature =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsFeature}, {
      &protobuf_dc_5frpc_2eproto::scc_info_UserParam.base,}};

static void InitDefaultsUserParam() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_UserParam_default_instance_;
    new (ptr) ::proto::UserParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::UserParam::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UserParam =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUserParam}, {}};

static void InitDefaultsStorageReply() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_StorageReply_default_instance_;
    new (ptr) ::proto::StorageReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::StorageReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_StorageReply =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStorageReply}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Empty.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UpdateNotity.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Feature.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UserParam.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StorageReply.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UpdateNotity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UpdateNotity, employee_table_update_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UpdateNotity, storage_table_update_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::Feature, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::Feature, face_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, face_photo_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, face_feature_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, face_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, acquisition_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, face_score_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::StorageReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::StorageReply, is_success_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::proto::Empty)},
  { 5, -1, sizeof(::proto::UpdateNotity)},
  { 12, -1, sizeof(::proto::Feature)},
  { 18, -1, sizeof(::proto::UserParam)},
  { 30, -1, sizeof(::proto::StorageReply)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_Empty_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_UpdateNotity_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_Feature_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_UserParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_StorageReply_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "dc_rpc.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014dc_rpc.proto\022\005proto\"\007\n\005Empty\"K\n\014Update"
      "Notity\022\035\n\025employee_table_update\030\001 \001(\010\022\034\n"
      "\024storage_table_update\030\002 \001(\010\")\n\007Feature\022\036"
      "\n\004face\030\001 \001(\0132\020.proto.UserParam\"\225\001\n\tUserP"
      "aram\022\014\n\004name\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\004\022\022\n\nf"
      "ace_photo\030\003 \001(\t\022\024\n\014face_feature\030\004 \001(\014\022\021\n"
      "\tface_size\030\005 \001(\004\022\030\n\020acquisition_time\030\006 \001"
      "(\004\022\022\n\nface_score\030\007 \001(\r\"\"\n\014StorageReply\022\022"
      "\n\nis_success\030\001 \001(\0102\211\002\n\020LonganDataCenter\022"
      ">\n\023StorageEmployeeFace\022\020.proto.UserParam"
      "\032\023.proto.StorageReply\"\000\022>\n\023StorageStrang"
      "erFace\022\020.proto.UserParam\032\023.proto.Storage"
      "Reply\"\000\022<\n\030ExtractFaceRegTableDatas\022\014.pr"
      "oto.Empty\032\016.proto.Feature\"\0000\001\0227\n\016Registe"
      "rClient\022\014.proto.Empty\032\023.proto.UpdateNoti"
      "ty\"\0000\001B\022\n\016com.longan.rpcP\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 634);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dc_rpc.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_dc_5frpc_2eproto
namespace proto {

// ===================================================================

void Empty::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Empty::Empty()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_dc_5frpc_2eproto::scc_info_Empty.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Empty)
}
Empty::Empty(const Empty& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.Empty)
}

void Empty::SharedCtor() {
}

Empty::~Empty() {
  // @@protoc_insertion_point(destructor:proto.Empty)
  SharedDtor();
}

void Empty::SharedDtor() {
}

void Empty::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Empty::descriptor() {
  ::protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Empty& Empty::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_dc_5frpc_2eproto::scc_info_Empty.base);
  return *internal_default_instance();
}


void Empty::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Empty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool Empty::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.Empty)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Empty)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Empty)
  return false;
#undef DO_
}

void Empty::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Empty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.Empty)
}

::google::protobuf::uint8* Empty::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.Empty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.Empty)
  return target;
}

size_t Empty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Empty)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Empty::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.Empty)
  GOOGLE_DCHECK_NE(&from, this);
  const Empty* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Empty>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.Empty)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.Empty)
    MergeFrom(*source);
  }
}

void Empty::MergeFrom(const Empty& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Empty)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void Empty::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.Empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Empty::CopyFrom(const Empty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Empty::IsInitialized() const {
  return true;
}

void Empty::Swap(Empty* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Empty::InternalSwap(Empty* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Empty::GetMetadata() const {
  protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UpdateNotity::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UpdateNotity::kEmployeeTableUpdateFieldNumber;
const int UpdateNotity::kStorageTableUpdateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UpdateNotity::UpdateNotity()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_dc_5frpc_2eproto::scc_info_UpdateNotity.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.UpdateNotity)
}
UpdateNotity::UpdateNotity(const UpdateNotity& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&employee_table_update_, &from.employee_table_update_,
    static_cast<size_t>(reinterpret_cast<char*>(&storage_table_update_) -
    reinterpret_cast<char*>(&employee_table_update_)) + sizeof(storage_table_update_));
  // @@protoc_insertion_point(copy_constructor:proto.UpdateNotity)
}

void UpdateNotity::SharedCtor() {
  ::memset(&employee_table_update_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&storage_table_update_) -
      reinterpret_cast<char*>(&employee_table_update_)) + sizeof(storage_table_update_));
}

UpdateNotity::~UpdateNotity() {
  // @@protoc_insertion_point(destructor:proto.UpdateNotity)
  SharedDtor();
}

void UpdateNotity::SharedDtor() {
}

void UpdateNotity::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UpdateNotity::descriptor() {
  ::protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UpdateNotity& UpdateNotity::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_dc_5frpc_2eproto::scc_info_UpdateNotity.base);
  return *internal_default_instance();
}


void UpdateNotity::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.UpdateNotity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&employee_table_update_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&storage_table_update_) -
      reinterpret_cast<char*>(&employee_table_update_)) + sizeof(storage_table_update_));
  _internal_metadata_.Clear();
}

bool UpdateNotity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.UpdateNotity)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool employee_table_update = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &employee_table_update_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool storage_table_update = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &storage_table_update_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.UpdateNotity)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.UpdateNotity)
  return false;
#undef DO_
}

void UpdateNotity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.UpdateNotity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool employee_table_update = 1;
  if (this->employee_table_update() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->employee_table_update(), output);
  }

  // bool storage_table_update = 2;
  if (this->storage_table_update() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->storage_table_update(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.UpdateNotity)
}

::google::protobuf::uint8* UpdateNotity::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.UpdateNotity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool employee_table_update = 1;
  if (this->employee_table_update() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->employee_table_update(), target);
  }

  // bool storage_table_update = 2;
  if (this->storage_table_update() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->storage_table_update(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.UpdateNotity)
  return target;
}

size_t UpdateNotity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.UpdateNotity)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool employee_table_update = 1;
  if (this->employee_table_update() != 0) {
    total_size += 1 + 1;
  }

  // bool storage_table_update = 2;
  if (this->storage_table_update() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UpdateNotity::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.UpdateNotity)
  GOOGLE_DCHECK_NE(&from, this);
  const UpdateNotity* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UpdateNotity>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.UpdateNotity)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.UpdateNotity)
    MergeFrom(*source);
  }
}

void UpdateNotity::MergeFrom(const UpdateNotity& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.UpdateNotity)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.employee_table_update() != 0) {
    set_employee_table_update(from.employee_table_update());
  }
  if (from.storage_table_update() != 0) {
    set_storage_table_update(from.storage_table_update());
  }
}

void UpdateNotity::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.UpdateNotity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateNotity::CopyFrom(const UpdateNotity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.UpdateNotity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateNotity::IsInitialized() const {
  return true;
}

void UpdateNotity::Swap(UpdateNotity* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UpdateNotity::InternalSwap(UpdateNotity* other) {
  using std::swap;
  swap(employee_table_update_, other->employee_table_update_);
  swap(storage_table_update_, other->storage_table_update_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UpdateNotity::GetMetadata() const {
  protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Feature::InitAsDefaultInstance() {
  ::proto::_Feature_default_instance_._instance.get_mutable()->face_ = const_cast< ::proto::UserParam*>(
      ::proto::UserParam::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Feature::kFaceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Feature::Feature()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_dc_5frpc_2eproto::scc_info_Feature.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Feature)
}
Feature::Feature(const Feature& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_face()) {
    face_ = new ::proto::UserParam(*from.face_);
  } else {
    face_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:proto.Feature)
}

void Feature::SharedCtor() {
  face_ = NULL;
}

Feature::~Feature() {
  // @@protoc_insertion_point(destructor:proto.Feature)
  SharedDtor();
}

void Feature::SharedDtor() {
  if (this != internal_default_instance()) delete face_;
}

void Feature::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Feature::descriptor() {
  ::protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Feature& Feature::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_dc_5frpc_2eproto::scc_info_Feature.base);
  return *internal_default_instance();
}


void Feature::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Feature)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && face_ != NULL) {
    delete face_;
  }
  face_ = NULL;
  _internal_metadata_.Clear();
}

bool Feature::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.Feature)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .proto.UserParam face = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_face()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Feature)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Feature)
  return false;
#undef DO_
}

void Feature::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Feature)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .proto.UserParam face = 1;
  if (this->has_face()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_face(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.Feature)
}

::google::protobuf::uint8* Feature::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.Feature)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .proto.UserParam face = 1;
  if (this->has_face()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_face(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.Feature)
  return target;
}

size_t Feature::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Feature)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .proto.UserParam face = 1;
  if (this->has_face()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *face_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Feature::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.Feature)
  GOOGLE_DCHECK_NE(&from, this);
  const Feature* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Feature>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.Feature)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.Feature)
    MergeFrom(*source);
  }
}

void Feature::MergeFrom(const Feature& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Feature)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_face()) {
    mutable_face()->::proto::UserParam::MergeFrom(from.face());
  }
}

void Feature::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.Feature)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Feature::CopyFrom(const Feature& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Feature)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Feature::IsInitialized() const {
  return true;
}

void Feature::Swap(Feature* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Feature::InternalSwap(Feature* other) {
  using std::swap;
  swap(face_, other->face_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Feature::GetMetadata() const {
  protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UserParam::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UserParam::kNameFieldNumber;
const int UserParam::kUserIdFieldNumber;
const int UserParam::kFacePhotoFieldNumber;
const int UserParam::kFaceFeatureFieldNumber;
const int UserParam::kFaceSizeFieldNumber;
const int UserParam::kAcquisitionTimeFieldNumber;
const int UserParam::kFaceScoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserParam::UserParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_dc_5frpc_2eproto::scc_info_UserParam.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.UserParam)
}
UserParam::UserParam(const UserParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  face_photo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.face_photo().size() > 0) {
    face_photo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_photo_);
  }
  face_feature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.face_feature().size() > 0) {
    face_feature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_feature_);
  }
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&face_score_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(face_score_));
  // @@protoc_insertion_point(copy_constructor:proto.UserParam)
}

void UserParam::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_photo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_feature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&face_score_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(face_score_));
}

UserParam::~UserParam() {
  // @@protoc_insertion_point(destructor:proto.UserParam)
  SharedDtor();
}

void UserParam::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_photo_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_feature_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UserParam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UserParam::descriptor() {
  ::protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UserParam& UserParam::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_dc_5frpc_2eproto::scc_info_UserParam.base);
  return *internal_default_instance();
}


void UserParam::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.UserParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_photo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_feature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&face_score_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(face_score_));
  _internal_metadata_.Clear();
}

bool UserParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.UserParam)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.UserParam.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 user_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string face_photo = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_face_photo()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->face_photo().data(), static_cast<int>(this->face_photo().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.UserParam.face_photo"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes face_feature = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_face_feature()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 face_size = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &face_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 acquisition_time = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &acquisition_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 face_score = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &face_score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.UserParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.UserParam)
  return false;
#undef DO_
}

void UserParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.UserParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UserParam.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // uint64 user_id = 2;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->user_id(), output);
  }

  // string face_photo = 3;
  if (this->face_photo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->face_photo().data(), static_cast<int>(this->face_photo().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UserParam.face_photo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->face_photo(), output);
  }

  // bytes face_feature = 4;
  if (this->face_feature().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->face_feature(), output);
  }

  // uint64 face_size = 5;
  if (this->face_size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->face_size(), output);
  }

  // uint64 acquisition_time = 6;
  if (this->acquisition_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->acquisition_time(), output);
  }

  // uint32 face_score = 7;
  if (this->face_score() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->face_score(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.UserParam)
}

::google::protobuf::uint8* UserParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.UserParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UserParam.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // uint64 user_id = 2;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->user_id(), target);
  }

  // string face_photo = 3;
  if (this->face_photo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->face_photo().data(), static_cast<int>(this->face_photo().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UserParam.face_photo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->face_photo(), target);
  }

  // bytes face_feature = 4;
  if (this->face_feature().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->face_feature(), target);
  }

  // uint64 face_size = 5;
  if (this->face_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->face_size(), target);
  }

  // uint64 acquisition_time = 6;
  if (this->acquisition_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(6, this->acquisition_time(), target);
  }

  // uint32 face_score = 7;
  if (this->face_score() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->face_score(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.UserParam)
  return target;
}

size_t UserParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.UserParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string face_photo = 3;
  if (this->face_photo().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->face_photo());
  }

  // bytes face_feature = 4;
  if (this->face_feature().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->face_feature());
  }

  // uint64 user_id = 2;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->user_id());
  }

  // uint64 face_size = 5;
  if (this->face_size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->face_size());
  }

  // uint64 acquisition_time = 6;
  if (this->acquisition_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->acquisition_time());
  }

  // uint32 face_score = 7;
  if (this->face_score() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->face_score());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UserParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.UserParam)
  GOOGLE_DCHECK_NE(&from, this);
  const UserParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UserParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.UserParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.UserParam)
    MergeFrom(*source);
  }
}

void UserParam::MergeFrom(const UserParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.UserParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.face_photo().size() > 0) {

    face_photo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_photo_);
  }
  if (from.face_feature().size() > 0) {

    face_feature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_feature_);
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.face_size() != 0) {
    set_face_size(from.face_size());
  }
  if (from.acquisition_time() != 0) {
    set_acquisition_time(from.acquisition_time());
  }
  if (from.face_score() != 0) {
    set_face_score(from.face_score());
  }
}

void UserParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.UserParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserParam::CopyFrom(const UserParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.UserParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserParam::IsInitialized() const {
  return true;
}

void UserParam::Swap(UserParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserParam::InternalSwap(UserParam* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  face_photo_.Swap(&other->face_photo_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  face_feature_.Swap(&other->face_feature_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(user_id_, other->user_id_);
  swap(face_size_, other->face_size_);
  swap(acquisition_time_, other->acquisition_time_);
  swap(face_score_, other->face_score_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UserParam::GetMetadata() const {
  protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StorageReply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StorageReply::kIsSuccessFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StorageReply::StorageReply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_dc_5frpc_2eproto::scc_info_StorageReply.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.StorageReply)
}
StorageReply::StorageReply(const StorageReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  is_success_ = from.is_success_;
  // @@protoc_insertion_point(copy_constructor:proto.StorageReply)
}

void StorageReply::SharedCtor() {
  is_success_ = false;
}

StorageReply::~StorageReply() {
  // @@protoc_insertion_point(destructor:proto.StorageReply)
  SharedDtor();
}

void StorageReply::SharedDtor() {
}

void StorageReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StorageReply::descriptor() {
  ::protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StorageReply& StorageReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_dc_5frpc_2eproto::scc_info_StorageReply.base);
  return *internal_default_instance();
}


void StorageReply::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.StorageReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  is_success_ = false;
  _internal_metadata_.Clear();
}

bool StorageReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.StorageReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool is_success = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_success_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.StorageReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.StorageReply)
  return false;
#undef DO_
}

void StorageReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.StorageReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool is_success = 1;
  if (this->is_success() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_success(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.StorageReply)
}

::google::protobuf::uint8* StorageReply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.StorageReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool is_success = 1;
  if (this->is_success() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_success(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.StorageReply)
  return target;
}

size_t StorageReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.StorageReply)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool is_success = 1;
  if (this->is_success() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StorageReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.StorageReply)
  GOOGLE_DCHECK_NE(&from, this);
  const StorageReply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StorageReply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.StorageReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.StorageReply)
    MergeFrom(*source);
  }
}

void StorageReply::MergeFrom(const StorageReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.StorageReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.is_success() != 0) {
    set_is_success(from.is_success());
  }
}

void StorageReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.StorageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StorageReply::CopyFrom(const StorageReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.StorageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StorageReply::IsInitialized() const {
  return true;
}

void StorageReply::Swap(StorageReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StorageReply::InternalSwap(StorageReply* other) {
  using std::swap;
  swap(is_success_, other->is_success_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StorageReply::GetMetadata() const {
  protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::Empty* Arena::CreateMaybeMessage< ::proto::Empty >(Arena* arena) {
  return Arena::CreateInternal< ::proto::Empty >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::UpdateNotity* Arena::CreateMaybeMessage< ::proto::UpdateNotity >(Arena* arena) {
  return Arena::CreateInternal< ::proto::UpdateNotity >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::Feature* Arena::CreateMaybeMessage< ::proto::Feature >(Arena* arena) {
  return Arena::CreateInternal< ::proto::Feature >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::UserParam* Arena::CreateMaybeMessage< ::proto::UserParam >(Arena* arena) {
  return Arena::CreateInternal< ::proto::UserParam >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::StorageReply* Arena::CreateMaybeMessage< ::proto::StorageReply >(Arena* arena) {
  return Arena::CreateInternal< ::proto::StorageReply >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
