// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dc_rpc.proto

#include "dc_rpc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_dc_5frpc_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_dc_5frpc_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_UserParam;
}  // namespace protobuf_dc_5frpc_2eproto
namespace proto {
class ExtractFaceParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExtractFaceParam>
      _instance;
} _ExtractFaceParam_default_instance_;
class UserParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UserParam>
      _instance;
} _UserParam_default_instance_;
class StorageReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StorageReply>
      _instance;
} _StorageReply_default_instance_;
}  // namespace proto
namespace protobuf_dc_5frpc_2eproto {
static void InitDefaultsExtractFaceParam() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_ExtractFaceParam_default_instance_;
    new (ptr) ::proto::ExtractFaceParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::ExtractFaceParam::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ExtractFaceParam =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsExtractFaceParam}, {}};

static void InitDefaultsUserParam() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_UserParam_default_instance_;
    new (ptr) ::proto::UserParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::UserParam::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UserParam =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUserParam}, {}};

static void InitDefaultsStorageReply() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_StorageReply_default_instance_;
    new (ptr) ::proto::StorageReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::StorageReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_StorageReply =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsStorageReply}, {
      &protobuf_dc_5frpc_2eproto::scc_info_UserParam.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ExtractFaceParam.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UserParam.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StorageReply.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ExtractFaceParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::ExtractFaceParam, count_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, face_photo_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, face_feature_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, face_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, acquisition_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::UserParam, face_score_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::StorageReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::StorageReply, is_success_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::StorageReply, face_reg_tables_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::proto::ExtractFaceParam)},
  { 6, -1, sizeof(::proto::UserParam)},
  { 18, -1, sizeof(::proto::StorageReply)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_ExtractFaceParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_UserParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_StorageReply_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "dc_rpc.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014dc_rpc.proto\022\005proto\"!\n\020ExtractFacePara"
      "m\022\r\n\005count\030\001 \001(\r\"\225\001\n\tUserParam\022\014\n\004name\030\001"
      " \001(\t\022\017\n\007user_id\030\002 \001(\004\022\022\n\nface_photo\030\003 \001("
      "\t\022\024\n\014face_feature\030\004 \001(\014\022\021\n\tface_size\030\005 \001"
      "(\004\022\030\n\020acquisition_time\030\006 \001(\004\022\022\n\nface_sco"
      "re\030\007 \001(\r\"M\n\014StorageReply\022\022\n\nis_success\030\001"
      " \001(\010\022)\n\017face_reg_tables\030\002 \003(\0132\020.proto.Us"
      "erParam2\336\001\n\020LonganDataCenter\022>\n\023StorageE"
      "mployeeFace\022\020.proto.UserParam\032\023.proto.St"
      "orageReply\"\000\022>\n\023StorageStrangerFace\022\020.pr"
      "oto.UserParam\032\023.proto.StorageReply\"\000\022J\n\030"
      "ExtractFaceRegTableDatas\022\027.proto.Extract"
      "FaceParam\032\023.proto.StorageReply\"\000B\022\n\016com."
      "longan.rpcP\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 540);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dc_rpc.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_dc_5frpc_2eproto
namespace proto {

// ===================================================================

void ExtractFaceParam::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExtractFaceParam::kCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExtractFaceParam::ExtractFaceParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_dc_5frpc_2eproto::scc_info_ExtractFaceParam.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.ExtractFaceParam)
}
ExtractFaceParam::ExtractFaceParam(const ExtractFaceParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  count_ = from.count_;
  // @@protoc_insertion_point(copy_constructor:proto.ExtractFaceParam)
}

void ExtractFaceParam::SharedCtor() {
  count_ = 0u;
}

ExtractFaceParam::~ExtractFaceParam() {
  // @@protoc_insertion_point(destructor:proto.ExtractFaceParam)
  SharedDtor();
}

void ExtractFaceParam::SharedDtor() {
}

void ExtractFaceParam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ExtractFaceParam::descriptor() {
  ::protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ExtractFaceParam& ExtractFaceParam::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_dc_5frpc_2eproto::scc_info_ExtractFaceParam.base);
  return *internal_default_instance();
}


void ExtractFaceParam::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ExtractFaceParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  count_ = 0u;
  _internal_metadata_.Clear();
}

bool ExtractFaceParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.ExtractFaceParam)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 count = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.ExtractFaceParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.ExtractFaceParam)
  return false;
#undef DO_
}

void ExtractFaceParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.ExtractFaceParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 count = 1;
  if (this->count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->count(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.ExtractFaceParam)
}

::google::protobuf::uint8* ExtractFaceParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.ExtractFaceParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 count = 1;
  if (this->count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->count(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.ExtractFaceParam)
  return target;
}

size_t ExtractFaceParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.ExtractFaceParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 count = 1;
  if (this->count() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->count());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExtractFaceParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.ExtractFaceParam)
  GOOGLE_DCHECK_NE(&from, this);
  const ExtractFaceParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ExtractFaceParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.ExtractFaceParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.ExtractFaceParam)
    MergeFrom(*source);
  }
}

void ExtractFaceParam::MergeFrom(const ExtractFaceParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.ExtractFaceParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.count() != 0) {
    set_count(from.count());
  }
}

void ExtractFaceParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.ExtractFaceParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExtractFaceParam::CopyFrom(const ExtractFaceParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ExtractFaceParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExtractFaceParam::IsInitialized() const {
  return true;
}

void ExtractFaceParam::Swap(ExtractFaceParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExtractFaceParam::InternalSwap(ExtractFaceParam* other) {
  using std::swap;
  swap(count_, other->count_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ExtractFaceParam::GetMetadata() const {
  protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UserParam::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UserParam::kNameFieldNumber;
const int UserParam::kUserIdFieldNumber;
const int UserParam::kFacePhotoFieldNumber;
const int UserParam::kFaceFeatureFieldNumber;
const int UserParam::kFaceSizeFieldNumber;
const int UserParam::kAcquisitionTimeFieldNumber;
const int UserParam::kFaceScoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserParam::UserParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_dc_5frpc_2eproto::scc_info_UserParam.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.UserParam)
}
UserParam::UserParam(const UserParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  face_photo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.face_photo().size() > 0) {
    face_photo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_photo_);
  }
  face_feature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.face_feature().size() > 0) {
    face_feature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_feature_);
  }
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&face_score_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(face_score_));
  // @@protoc_insertion_point(copy_constructor:proto.UserParam)
}

void UserParam::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_photo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_feature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&face_score_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(face_score_));
}

UserParam::~UserParam() {
  // @@protoc_insertion_point(destructor:proto.UserParam)
  SharedDtor();
}

void UserParam::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_photo_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_feature_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UserParam::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UserParam::descriptor() {
  ::protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UserParam& UserParam::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_dc_5frpc_2eproto::scc_info_UserParam.base);
  return *internal_default_instance();
}


void UserParam::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.UserParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_photo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  face_feature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&face_score_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(face_score_));
  _internal_metadata_.Clear();
}

bool UserParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.UserParam)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.UserParam.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 user_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string face_photo = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_face_photo()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->face_photo().data(), static_cast<int>(this->face_photo().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.UserParam.face_photo"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes face_feature = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_face_feature()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 face_size = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &face_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 acquisition_time = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &acquisition_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 face_score = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &face_score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.UserParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.UserParam)
  return false;
#undef DO_
}

void UserParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.UserParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UserParam.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // uint64 user_id = 2;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->user_id(), output);
  }

  // string face_photo = 3;
  if (this->face_photo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->face_photo().data(), static_cast<int>(this->face_photo().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UserParam.face_photo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->face_photo(), output);
  }

  // bytes face_feature = 4;
  if (this->face_feature().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->face_feature(), output);
  }

  // uint64 face_size = 5;
  if (this->face_size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->face_size(), output);
  }

  // uint64 acquisition_time = 6;
  if (this->acquisition_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->acquisition_time(), output);
  }

  // uint32 face_score = 7;
  if (this->face_score() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->face_score(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.UserParam)
}

::google::protobuf::uint8* UserParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.UserParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UserParam.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // uint64 user_id = 2;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->user_id(), target);
  }

  // string face_photo = 3;
  if (this->face_photo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->face_photo().data(), static_cast<int>(this->face_photo().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.UserParam.face_photo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->face_photo(), target);
  }

  // bytes face_feature = 4;
  if (this->face_feature().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->face_feature(), target);
  }

  // uint64 face_size = 5;
  if (this->face_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->face_size(), target);
  }

  // uint64 acquisition_time = 6;
  if (this->acquisition_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(6, this->acquisition_time(), target);
  }

  // uint32 face_score = 7;
  if (this->face_score() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->face_score(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.UserParam)
  return target;
}

size_t UserParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.UserParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string face_photo = 3;
  if (this->face_photo().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->face_photo());
  }

  // bytes face_feature = 4;
  if (this->face_feature().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->face_feature());
  }

  // uint64 user_id = 2;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->user_id());
  }

  // uint64 face_size = 5;
  if (this->face_size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->face_size());
  }

  // uint64 acquisition_time = 6;
  if (this->acquisition_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->acquisition_time());
  }

  // uint32 face_score = 7;
  if (this->face_score() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->face_score());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UserParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.UserParam)
  GOOGLE_DCHECK_NE(&from, this);
  const UserParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UserParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.UserParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.UserParam)
    MergeFrom(*source);
  }
}

void UserParam::MergeFrom(const UserParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.UserParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.face_photo().size() > 0) {

    face_photo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_photo_);
  }
  if (from.face_feature().size() > 0) {

    face_feature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.face_feature_);
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.face_size() != 0) {
    set_face_size(from.face_size());
  }
  if (from.acquisition_time() != 0) {
    set_acquisition_time(from.acquisition_time());
  }
  if (from.face_score() != 0) {
    set_face_score(from.face_score());
  }
}

void UserParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.UserParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserParam::CopyFrom(const UserParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.UserParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserParam::IsInitialized() const {
  return true;
}

void UserParam::Swap(UserParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserParam::InternalSwap(UserParam* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  face_photo_.Swap(&other->face_photo_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  face_feature_.Swap(&other->face_feature_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(user_id_, other->user_id_);
  swap(face_size_, other->face_size_);
  swap(acquisition_time_, other->acquisition_time_);
  swap(face_score_, other->face_score_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UserParam::GetMetadata() const {
  protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StorageReply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StorageReply::kIsSuccessFieldNumber;
const int StorageReply::kFaceRegTablesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StorageReply::StorageReply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_dc_5frpc_2eproto::scc_info_StorageReply.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.StorageReply)
}
StorageReply::StorageReply(const StorageReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      face_reg_tables_(from.face_reg_tables_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  is_success_ = from.is_success_;
  // @@protoc_insertion_point(copy_constructor:proto.StorageReply)
}

void StorageReply::SharedCtor() {
  is_success_ = false;
}

StorageReply::~StorageReply() {
  // @@protoc_insertion_point(destructor:proto.StorageReply)
  SharedDtor();
}

void StorageReply::SharedDtor() {
}

void StorageReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StorageReply::descriptor() {
  ::protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StorageReply& StorageReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_dc_5frpc_2eproto::scc_info_StorageReply.base);
  return *internal_default_instance();
}


void StorageReply::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.StorageReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  face_reg_tables_.Clear();
  is_success_ = false;
  _internal_metadata_.Clear();
}

bool StorageReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.StorageReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool is_success = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_success_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .proto.UserParam face_reg_tables = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_face_reg_tables()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.StorageReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.StorageReply)
  return false;
#undef DO_
}

void StorageReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.StorageReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool is_success = 1;
  if (this->is_success() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_success(), output);
  }

  // repeated .proto.UserParam face_reg_tables = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->face_reg_tables_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->face_reg_tables(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.StorageReply)
}

::google::protobuf::uint8* StorageReply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.StorageReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool is_success = 1;
  if (this->is_success() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_success(), target);
  }

  // repeated .proto.UserParam face_reg_tables = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->face_reg_tables_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->face_reg_tables(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.StorageReply)
  return target;
}

size_t StorageReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.StorageReply)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .proto.UserParam face_reg_tables = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->face_reg_tables_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->face_reg_tables(static_cast<int>(i)));
    }
  }

  // bool is_success = 1;
  if (this->is_success() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StorageReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.StorageReply)
  GOOGLE_DCHECK_NE(&from, this);
  const StorageReply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StorageReply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.StorageReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.StorageReply)
    MergeFrom(*source);
  }
}

void StorageReply::MergeFrom(const StorageReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.StorageReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  face_reg_tables_.MergeFrom(from.face_reg_tables_);
  if (from.is_success() != 0) {
    set_is_success(from.is_success());
  }
}

void StorageReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.StorageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StorageReply::CopyFrom(const StorageReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.StorageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StorageReply::IsInitialized() const {
  return true;
}

void StorageReply::Swap(StorageReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StorageReply::InternalSwap(StorageReply* other) {
  using std::swap;
  CastToBase(&face_reg_tables_)->InternalSwap(CastToBase(&other->face_reg_tables_));
  swap(is_success_, other->is_success_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StorageReply::GetMetadata() const {
  protobuf_dc_5frpc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dc_5frpc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::ExtractFaceParam* Arena::CreateMaybeMessage< ::proto::ExtractFaceParam >(Arena* arena) {
  return Arena::CreateInternal< ::proto::ExtractFaceParam >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::UserParam* Arena::CreateMaybeMessage< ::proto::UserParam >(Arena* arena) {
  return Arena::CreateInternal< ::proto::UserParam >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::StorageReply* Arena::CreateMaybeMessage< ::proto::StorageReply >(Arena* arena) {
  return Arena::CreateInternal< ::proto::StorageReply >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
